#!/bin/bash
# This script is useful to do an Admixture analysis. The script assume that you have the executable of the program "admixture32" and the file *12.ped generated by plink in the same working directory in which you run the analysis.


echo "Starts at:"
date

for K in {1..9}; do ./admixture32 --cv=100 Caribe_12.ped $K -j6 | tee log${K}.out; done 

echo "Ends at:"
date







