#!/bin/bash
# This script is useful to do an Admixture analysis. The script assume that you have the executable of the program "admixture32" and the file *12.ped generated by plink in the same working directory in which you run the analysis.
# You will define the values for the variable "K" depend on the number of genetic groups that you want to test. We recommend test as many groups as sampling sites you have and consider one more.
# Also you can change de "--cv", see the manual for more information.
# At the end of the analysis you must put the "CV" of the all output files "*log" in a new file in order to do graphics.

echo "Starts at:"
date

for K in {1..9}; do ./admixture32 --cv=100 Caribe_12.ped $K -j6 | tee log${K}.out; done 

echo "Ends at:"
date







